### ISSUE TITLE
IOException leaking from lib/TransferControllers/TransferWriters/StreamedWriter.cs

### ISSUE THREAD

**Issue by lamolley1** [Azure/azure-storage-net-data-movement#142]
### Which service(blob, file) does this issue concern? 
Blob to file copy.
 
### Which version of the SDK was used?
0.2.0, but from looking at the code this bug exists in the latest version

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.Net 4.5

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
Start a blob to file copy where the file system runs out of disk space.

### What problem was encountered?

 This is the line where the IOException was thrown from.
https://github.com/Azure/azure-storage-net-data-movement/blob/7c8258a8ffbef96b10ebdabd14f5d129048ce1de/lib/TransferControllers/TransferWriters/StreamedWriter.cs#L223

Here is the strack trace I got:
IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SetLengthCore(Int64 value)
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferControllers.StreamedWriter.<HandleOutputStreamAsync>b__3()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferControllers.StreamedWriter.<HandleOutputStreamAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferControllers.StreamedWriter.<DoWorkInternalAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferControllers.SyncTransferController.<DoWorkInternalAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferControllers.TransferControllerBase.<DoWorkAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferScheduler.<ExecuteJobInternalAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.DataMovement.SingleObjectTransfer.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferManager.<DoTransfer>d__2.MoveNext()
 
### Have you found a mitigation/solution?

Currently, we do not have a mitigation. We could catch IOException in our code that's calls the DataMovement library. The issue here is that since the library crashed with an unknown exception, we are holding onto the file handle for some time and we get issue trying to clean up the failed copied file.

**Comment by EmmaZhu** [comment]
@lamolley1 
What would you want DMLib to resolve? To handle IOException first to avoid unrecognized exception to crash a tool, or to release the file handle to let you be able to clean up the failed target file?

I just tried with latest DMLib with code like following:
```
            try
            {
                TransferManager.DownloadAsync(blob, "destination", null, transferContext).Wait();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
```
In DMLib, if there's any error happens, it can release the file handle reserved. With the above code, when I debugged to code line of `Console.WriteLine(ex);` I can successfully remove the "destination" file.

Would you like to have a try with latest DMLib?

**Comment by lamolley1** [comment]
Is there a particular version of DMLib where it was added that any exception will release the file handle?

I'm fine with going to latest and trying to catch the IOException. However, is it in the design of DMLib to leak IOExceptions? We are expecting transfer and storage exceptions. I think the bug should be fixed. We prefer to not catch generic exceptions in our code base. This helps us distinguish between expected error cases and unexpected errors that are bugs in the library.

**Comment by EmmaZhu** [comment]
@lamolley1,
DMLib is designed to release the file handle when there's any exception happens, it should not leak any handle. But if you encountered handle leak in an older version, it'd be better to upgrade to latest DMLib. I've just tested with latest DMLib that it can release file handle when there's exception happens.

As for the exception handling, current design is to throw out the origin exception out when we cannot recognize or add more detailed error message to the exception, or DMLib can only wrap these unrecognized exceptions within transfer exception with unkown error and you'd need to check it's internal error for detailed error messages. It may not be a good way to distinguish each exception.
