### ISSUE TITLE
Cannot Download blobs from azureedge.net

### ISSUE THREAD

**Issue by KiranBabu-Kirando** [Azure/azure-storage-net-data-movement#212]
### Which service(blob, file) does this issue concern? 
Blob files from azureedge.net
 
### Which version of the SDK was used?
1.2.0

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.Net Framework

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
            try
            {
                var sourceUri = @"https://xxxx.azureedge.net/58b07c18-f267-48fe-a57f-1eaccf764f18/Unity.dmg?sp=r&st=2020-02-25T20:54:19Z&se=2020-06-26T03:54:19Z&spr=https&sv=2019-02-02&sr=b&sig=xxxxxxxxxxx";

                var sourceBlob = new CloudBlob(new Uri(sourceUri));
                var destDir = @"C:\Temp\Unity.dmg";

                var guid = "21aa05ad-539e-492f-b671-925847806f16";

                DownloadOptions options = new DownloadOptions();
                options.DisableContentMD5Validation = true;

                // Setup the number of the concurrent operations
                TransferManager.Configurations.ParallelOperations = 64;
                // Setup the transfer context and track the upload progress
                SingleTransferContext context = new SingleTransferContext();
                context.ProgressHandler = new Progress<TransferStatus>((progress) =>
                {
                    Console.WriteLine("Bytes downloaded: {0}", progress.BytesTransferred);
                });
                context.ClientRequestId = guid.ToString();

                // Upload a local blob
                var task = TransferManager.DownloadAsync(
                    sourceBlob, destDir, options, context, CancellationToken.None);
                task.Wait();
            }
            catch (Exception ex)
            {
            }
 
### What problem was encountered?
When declaring sourceblob as "new CloudBlockBlob(new Uri(sourceUri));". The below error is encountered
Unexpected response code, Expected:PartialContent, Received:OK

   at Microsoft.Azure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBasedBlobReader.<DownloadChunkAsync>d__17.MoveNext() in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferControllers\TransferReaders\BlockBasedBlobReader.cs:line 350
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBasedBlobReader.<DownloadBlockBlobAsync>d__16.MoveNext() in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferControllers\TransferReaders\BlockBasedBlobReader.cs:line 312
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBasedBlobReader.<FetchAttributeAsync>d__15.MoveNext() in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferControllers\TransferReaders\BlockBasedBlobReader.cs:line 230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.DataMovement.TransferControllers.BlockBasedBlobReader.<DoWorkInternalAsync>d__13.MoveNext() in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferControllers\TransferReaders\BlockBasedBlobReader.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.DataMovement.TransferControllers.SyncTransferController.<DoWorkInternalAsync>d__14.MoveNext() in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferControllers\SyncTransferController.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.DataMovement.TransferControllers.TransferControllerBase.<DoWorkAsync>d__34.MoveNext() in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferControllers\TransferControllerBase.cs:line 214
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.DataMovement.TransferScheduler.<ExecuteJobInternalAsync>d__28.MoveNext() in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferScheduler.cs:line 218

When declaring sourceblob as "new CloudBlob(new Uri(sourceUri));". The below error is encountered
The given blob type Unspecified is not supported.

   at Microsoft.Azure.Storage.DataMovement.TransferControllers.SyncTransferController.GetReader(TransferLocation sourceLocation) in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferControllers\SyncTransferController.cs:line 199
   at Microsoft.Azure.Storage.DataMovement.TransferControllers.SyncTransferController..ctor(TransferScheduler transferScheduler, TransferJob transferJob, CancellationToken userCancellationToken) in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferControllers\SyncTransferController.cs:line 48
   at Microsoft.Azure.Storage.DataMovement.TransferScheduler.GenerateTransferConstroller(TransferScheduler transferScheduler, TransferJob transferJob, CancellationToken cancellationToken) in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferScheduler.cs:line 520
   at Microsoft.Azure.Storage.DataMovement.TransferScheduler.<ExecuteJobInternalAsync>d__28.MoveNext() in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferScheduler.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.DataMovement.SingleObjectTransfer.<ExecuteAsync>d__17.MoveNext() in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferJobs\SingleObjectTransfer.cs:line 267
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.DataMovement.TransferManager.<DoTransfer>d__92.MoveNext() in C:\Local\Jenkins\jobs\DMLib_FileACL\workspace\lib\TransferManager.cs:line 1773
 
### Have you found a mitigation/solution?
No. But the file gets downloaded using edge browser.

**Comment by jiacfan** [comment]
Hi, @KiranBabu-Kirando:

From the the call stack and phenomenon, it looks like when date is hosted by azureedge.net, the REST API works a bit different from origin service(Storage).

When data is fetched by edge, it might directly call [GET blob](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob) without `Range`, in this case entire file is downloaded sequentially.

When data is fetched by DMLib, it tries to download file chunk by chunk, i.e. call GET blob with range specificed. In this case, Status 206 is expected, while 200 is actually returned.

As I don't have file on azureedge.net, would you help to do an experiment: GET blob with a specific file range with Edge? And check if 200 is returned.

To work around, please try to directly use .Net SDK to download the entire file.

Add @EmmaZhu for visibility of this scenario.

Thanks,
Jiachen

**Comment by jiacfan** [comment]
@KiranBabu-Kirando, there should be configurations related to Large file optimization in CDN side, which could influence 200 or 206 returned when Get with range. FYI, and worth to have a check.

**Comment by jiacfan** [comment]
Close as no reply for 3 months, please feel free to let us know if more helps are needed.
