### ISSUE TITLE
Add support for .net core

### ISSUE THREAD

**Issue by caserzer** [Azure/azure-storage-net-data-movement#30]
I'm trying to upload / download file from blob storage to nano servers on azure, but found no tools can be used directly. Since the azure storage assembly and newtonsoft.json has support the .net core, please add .net core support!

**Comment by vinjiang** [comment]
@caserzer ,we have considered this option and are doing some evaluation work. Please stay tuned. Thanks!

**Comment by RHAD1969** [comment]
Same issue with UWP apps. The nuget packages installs, but the Microsoft.Azure.Storage.DataMovement namespace is not available. Please consider adding .net core support.

**Comment by brandonrisell** [comment]
I'll add my vote, I'd love to see .net standard support.

**Comment by cschotte** [comment]
+1 for .net core

**Comment by blueww** [comment]
DMlib already has .net core version from 0.3 release.

**Comment by qqwertyasdf** [comment]
Hi I'm trying to use this library in a UWP app. I used Nuget to get it with no errors so I assume it should be usable in UWP apps. But on running it, after download completes I get an exception:

`Message: Could not load file or assembly 'System.Threading.ThreadPool, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
StackTrace:    at Microsoft.WindowsAzure.Storage.DataMovement.TransferControllers.TransferControllerBase.FinishCallbackHandler(Exception exception)
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferControllers.TransferControllerBase.<DoWorkAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferScheduler.<DoControllerWork>d__31.MoveNext()`

The code that results in the above is (I monitor context progress and it happens after the whole file has been downloaded)
```
...
await TransferManager.DownloadAsync(latestUpd, fs, options, context);
...
```

If I use the normal Azure storage API to download it works with no exception:
```
...
await latestUpd.DownloadToStreamAsync(fs);
...
```

For UWP ThreadPool is under the namespace Windows.System.Threading whereas for traditional .Net it's in System.Threading. So is this a bug or do I have to configure something?

Thanks

**Comment by EmmaZhu** [comment]
@qqwertyasdf 
DataMovement doesn't support UWP yet. We'll definitely consider to support it.

Thanks
Emma

**Comment by cmassemin** [comment]
Is there a Roadmap for UWP Support?

**Comment by vinjiang** [comment]
@EmmaZhu , let's track UWP request in an a different thread.

**Comment by EmmaZhu** [comment]
[https://github.com/Azure/azure-storage-net-data-movement/issues/30](url)

**Comment by EmmaZhu** [comment]
Tracking UWP support in a different thread: [https://github.com/Azure/azure-storage-net-data-movement/issues/30](url)

**Comment by EmmaZhu** [comment]
Tracking UWP support in new thread. [https://github.com/Azure/azure-storage-net-data-movement/issues/131](url)
